### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by AlecRust** [growquest-technologies/wplyr-media-block#1]
Thanks for this project, after a lot of searching this is the only working Plyr WordPress plugin for protecting YouTube videos.

With debug mode enabled when this plugin is installed I get dozens of this output at the top of every page, in WP Admin and main site:

```
Notice: Trying to access array offset on value of type null in /var/www/html/wp-content/plugins/wplyr-media-block/vendor/leafo/scssphp/src/Compiler.php on line 2556
```

I assume upgrading to the latest version of [scssphp](https://github.com/scssphp/scssphp) will fix this?

**Comment by jeetsaha86** [comment]
Issue has been addressed in the latest version.
